---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: golang
    commands:
      - make build
      - make test

  - name: docker
    image: plugins/docker
    settings:
      repo: hello-app
