---
kind: pipeline
name: default

steps:
  - name: build
    image: golang
    commands:
      - make build
      - make test

  - name: docker
    image: plugins/docker
    settings:
      repo: hello-app
      registry: "localhost:5000"
